import javax.swing.*;
import java.awt.*;

public class LogViewer extends JDialog
{
    private JPanel contentPane;
    private JTextArea textArea1;
    private JButton OKButton;
    private JButton buttonOK;

    public LogViewer ()
    {
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(buttonOK);
        OKButton.addActionListener(e -> dispose());
        textArea1.setText(Logger.getContent());
    }

    public static void main (String[] args)
    {
        LogViewer dialog = new LogViewer();
        dialog.pack();
        dialog.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$ ()
    {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        contentPane.setMinimumSize(new Dimension(300, 200));
        contentPane.setPreferredSize(new Dimension(300, 200));
        OKButton = new JButton();
        OKButton.setText("OK");
        contentPane.add(OKButton, BorderLayout.SOUTH);
        final JScrollPane scrollPane1 = new JScrollPane();
        contentPane.add(scrollPane1, BorderLayout.CENTER);
        textArea1 = new JTextArea();
        scrollPane1.setViewportView(textArea1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$ ()
    {
        return contentPane;
    }
}
